# 服务端口
http:
  port: 29091
database:
  # 数据库类型 取值mysql或postgresql
  driver: mysql
  # 数据库IP
  host: 192.168.168.166
  # 数据库端口
  port: 3306
  # 数据库名称
  name: db_09
  # 用户名
  user: hwuser
  # 密码
  password: wXh%?2;zc3=4